### ISSUE TITLE
library installation 

### ISSUE THREAD

**Issue by jimegon17** [ScPoEcon/ScPoEconometrics#101]
When installing the ScPoEconometrics library 
`if (!require("devtools")) install.packages("devtools")
library(devtools)
install_github(repo = "ScPoEcon/ScPoEconometrics")`
the following error appears:
`package ‘colorspace’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘colorspace’`

Moreover, after running `library(ScPoEconometrics)`
an error appears:
`Error in library(ScPoEconometrics) : 
  there is no package called ‘ScPoEconometrics’`

**Comment by floswald** [comment]
Can you please post `sessionInfo()` after you execute those commands?

**Comment by jimegon17** [comment]
Thank you for the fast response. I ran 
`if` (!require("devtools")) install.packages("devtools")
library(devtools)
install_github(repo = "ScPoEcon/ScPoEconometrics")
sessionInfo()`
Output:
`R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] usethis_1.4.0   devtools_2.0.1  ggplot2_3.1.0   AER_1.2-6       survival_2.43-3 sandwich_2.5-0 
 [7] lmtest_0.9-36   zoo_1.8-4       car_3.0-2       carData_3.0-2  

loaded via a namespace (and not attached):
Error in x[["Version"]] : subscript out of bounds
In addition: Warning message:
In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'colorspace' is missing or broken`

**Comment by jimegon17** [comment]
After I reinstalled package 'colorspace', everything worked.

**Comment by floswald** [comment]
👍
