### ISSUE TITLE
runTutorial() not working properly: invalid 'file' argument

### ISSUE THREAD

**Issue by mattiaguerini** [ScPoEcon/ScPoEconometrics#103]
Hello!

Just installed and tested the package. 
When I run the `runTutorial()` function, I obtain the following error:
> Error in file.exists(dep$src$file) : invalid 'file' argument

E.g.: 
`runTutorial('chapter2')`
> Error in file.exists(dep$src$file) : invalid 'file' argument

FYI:
`sessionInfo()`
> R version 3.5.0 (2018-04-23)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS  10.14.2
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods  
> [7] base     
> 
> other attached packages:
>  [1] reshape2_1.4.3         datasauRus_0.1.4      
>  [3] learnr_0.9.2.9000      bindrcpp_0.2.2        
>  [5] plotly_4.7.1           ggplot2_3.1.0         
>  [7] dplyr_0.7.8            mvtnorm_1.0-8         
>  [9] shiny_1.2.0            ScPoEconometrics_0.2.1
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.3.1         tidyr_0.8.2        jsonlite_1.5      
>  [4] viridisLite_0.3.0  splines_3.5.0      Ecfun_0.1-7       
>  [7] modelr_0.1.2       assertthat_0.2.0   cellranger_1.1.0  
> [10] yaml_2.2.0         pillar_1.2.2       backports_1.1.2   
> [13] lattice_0.20-35    glue_1.3.0         digest_0.6.18     
> [16] RColorBrewer_1.1-2 promises_1.0.1     rvest_0.3.2       
> [19] colorspace_1.3-2   htmltools_0.3.6    httpuv_1.4.5      
> [22] Matrix_1.2-14      plyr_1.8.4         psych_1.8.4       
> [25] pkgconfig_2.0.2    broom_0.4.4        haven_1.1.0       
> [28] fda_2.4.8          bookdown_0.7       purrr_0.2.5       
> [31] xtable_1.8-3       webshot_0.5.1      scales_1.0.0      
> [34] jpeg_0.1-8         later_0.7.5        TeachingDemos_2.10
> [37] tibble_1.4.2       withr_2.1.2        tidyverse_1.2.1   
> [40] lazyeval_0.2.1     mnormt_1.5-5       readxl_1.1.0      
> [43] magrittr_1.5       mime_0.6           evaluate_0.12     
> [46] nlme_3.1-137       MASS_7.3-49        xml2_1.2.0        
> [49] forcats_0.3.0      foreign_0.8-70     tools_3.5.0       
> [52] data.table_1.11.8  hms_0.4.2          stringr_1.3.1     
> [55] munsell_0.5.0      EnvStats_2.3.1     compiler_3.5.0    
> [58] rlang_0.3.0.1      grid_3.5.0         rappdirs_0.3.1    
> [61] htmlwidgets_1.3    crosstalk_1.0.0    rmarkdown_1.10.16 
> [64] Ecdat_0.3-1        gtable_0.2.0       markdown_0.8      
> [67] R6_2.3.0           lubridate_1.7.4    knitr_1.20        
> [70] bindr_0.1.1        rprojroot_1.3-2    readr_1.1.1       
> [73] stringi_1.2.4      parallel_3.5.0     Rcpp_1.0.0        
> [76] tidyselect_0.2.5   xfun_0.4   

Thanks for the support!
Best,
Mattia

**Comment by floswald** [comment]
ok let's try this:

1. close R
2. open R

```R
remove.packages("ScPoEconometrics")
library(devtools)
install_github("ScPoEcon/ScPoEconometrics")
```

**Comment by mattiaguerini** [comment]
Now it runs once. But if I re-run it, then it doesn’t work (providing the same error I obtained before). Does the command create a kind of “executable” file that I can find somewhere on my laptop?

**Comment by mattiaguerini** [comment]
The "rescaling" tutorial actually runs more than once. Hope that this info can help you understanding the issue.

**Comment by floswald** [comment]
i was able to reproduce this as well! posted an issue https://github.com/rstudio/shiny/issues/2307

**Comment by floswald** [comment]
really weird that this other tutorial runs...
