### ISSUE TITLE
Data for case studies /  exercises

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#105]
* https://github.com/fivethirtyeight/data/blob/master/airline-safety/README.md
* https://cerema.app.box.com/v/dvfplus-opendata/folder/77718179192
* https://opportunityinsights.org/course/

**Comment by floswald** [comment]
## house price data

1. download https://cerema.app.box.com/v/dvfplus-opendata/folder/77718179192
1. compute some statistics by region

**Comment by pvilledieu** [comment]
open source for data (replicating papers) : https://dataverse.harvard.edu/
