### ISSUE TITLE
ScPoEconometrics package not available (for R version 3.5.2) 

### ISSUE THREAD

**Issue by JulieAssaad** [ScPoEcon/ScPoEconometrics#107]
Hi, 
I am not able to access the 'ScPoEconometrics' package. It used to work before. Now the LaunchApp, runTutorial, and AboutApp are no longer working. So I uninstalled the package and tried reinstalling it. I go the following error:  "Warning in install.packages :   package ‘ScPoEconometrics’ is not available (for R version 3.5.2)"
What should I do to be able to access it?
Thank you!

**Comment by floswald** [comment]
Hi

Can you post the precise output and commands you issue to get the error? I
also need your sessionInfo() output here.

**Comment by JulieAssaad** [comment]
> install.packages('ScPoEconometrics')
Installing package into ‘C:/Users/lenovo/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ScPoEconometrics’ is not available (for R version 3.5.2)
>

**Comment by floswald** [comment]
this package is not on CRAN. you need to install it as detailed in the first chapter of the book. please close this issue if this resolves your problems.

**Comment by JulieAssaad** [comment]
Yes, I was able to download the package now thank you! But I am still encountering the initial problem with the launchApp() and runTutorial(). 
Example: 
1: aboutApp('reg_simple_arrows')
Invalid input, please try again

**Comment by JulieAssaad** [comment]
sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.2   R6_2.3.0         assertthat_0.2.0 cli_1.0.1       
 [5] tools_3.5.2      rstudioapi_0.9.0 yaml_2.2.0       memoise_1.1.0   
 [9] crayon_1.3.4     digest_0.6.18

**Comment by floswald** [comment]
it seems from you sessionInfo() that you didn't load the pacakge. you need
to do

library(ScPoEconometrics)
launchApp()
