### ISSUE TITLE
secion 6.3.1 confusing

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#112]

**Comment by floswald** [comment]
hey @nicolodalvit , 
what exactly did you find confusing here? I just read looked at it and it seems pretty clear to me.

**Comment by nicolodalvit** [comment]
Hi Florian, it seemed to me that many students had trouble understanding this section. There might be two reasons for this confusion:
1.  Expressions (6.5) and (6.6) are true only if x is normally distributed but this assumption is not explicitly mentioned in this section.
2.  Many people did not see the multiplication by the square root of n in (6.6) as intuitive and they did not understand where it was coming from. It might be easier for them if, before going to (6.6), they could see the steps from (6.5) to the z-score for the mean.
