### ISSUE TITLE
expand treatment of causality

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#113]
>I think that it would be useful to expand the treatment of causality. There should be a bigger section on reverse causality, the difference between causality and correlation and identification of a causal relationship in general. Correcting the final projects that Ollie and I have assigned to our students, I realized that many of them still lack a clear understanding of these concepts. Section 6.5 is clear and useful but maybe it should be part of a broader discussion on causality.

**Comment by floswald** [comment]
* add rubin's framework?
* find a simple example. effeciveness of drug? RCT or not?

**Comment by pvilledieu** [comment]
Ok so after thinking a bit, my proposal would be : 

1. Linear regression as a way to fit/describe/predict (linear) relationships between variables, OLS being the best linear (unbiased) estimator 
--> chapter 3 to 5 
2. Introduce linear regression as a statistical model (chapter 6.1 and 6.2) which allow us to : 
2.1. infer (true) population parameters from samples : notion of confidence interval, tests, ...
--> chapter 6.2.1 to 6.4 
2.2. investigate causal relationships : causality vs correlation, what assumptions have to be verified in our model, when can it be violated, ...?
--> new content about causality + chapter 6.5

Does it make sens for you @floswald ?

**Comment by floswald** [comment]
yes that sounds good to me. the only issue is that we will run out of time and won't be able to reach the new content in 2.2, unless we shorten/omit something else. what could that be? we could declare optional a couple of sections in the book, or make them shorter in the slides. most after 3.2 comes to mind.

**Comment by floswald** [comment]
solution:

* save time by removing regression restrictions (no intercept, standardized etc) from teh slides, but not the book
* corresponding quiz questions should be kept but marked optional
* chapter 3 slides *rescaling* stuff to be removed

**Comment by floswald** [comment]
* we could use the idea of DAGs as here on pag 68 http://scunning.com/cunningham_mixtape.pdf

**Comment by floswald** [comment]
example https://moderndive.com/5-regression.html#related-topics

**Comment by floswald** [comment]
https://cran.r-project.org/web/packages/ggdag/vignettes/intro-to-ggdag.html
