### ISSUE TITLE
go back to base R only - no dplyr

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#116]
* definitely start out with base R subsetting and aggregating
* then either a bit of data.table or dplyr to do `group_by`
* in particular in light of https://github.com/matloff/TidyverseSkeptic

## implications

* basically don't use tidyverse in chapter 2, which seems a small change (only doing a superficial introduction anyway)
* we'll have to go back to base-R for *aggregating* and doing some aggregate by group stuff. `aggregate` is not too bad actually.
* there was a fairly complete tutorial for dplyr data wrangling at the end of chapter 2. will have to go.

**Comment by vviers** [comment]
Hey! Interesting topic indeed.

I don't recall using much dplyr in the textbook, any particular section you're thinking about?

**Comment by floswald** [comment]
updated! :-)
