### ISSUE TITLE
Error loading `ScPoApps`

### ISSUE THREAD

**Issue by michelefioretti** [ScPoEcon/ScPoEconometrics#158]
Hi, I installed the `ScPoApps` as by the readme file running

```
if (!require(devtools)) {install.packages("devtools"); library(devtools)}
install_github(repo = "ScPoEcon/ScPoApps")

```
and updated all the packages that need update.  Then when I load the package I get the following error:

```
library(ScPoApps)
Error: package or namespace load failed for ‘ScPoApps’:
 .onLoad failed in loadNamespace() for 'broom', details:
  call: get0(oNam, envir = ns)
  error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/backports/R/backports.rdb' is corrupt
In addition: Warning message:
In get0(oNam, envir = ns) : internal error -3 in R_decompress1
```

I tried in two different machines, the error stays. Could you help me with that please?

**Comment by michelefioretti** [comment]
I get a similar error when I load `broom`

```
library(broom)
Error: package or namespace load failed for ‘broom’:
 .onLoad failed in loadNamespace() for 'broom', details:
  call: get0(oNam, envir = ns)
  error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/backports/R/backports.rdb' is corrupt
In addition: Warning messages:
1: package ‘broom’ was built under R version 3.6.2 
2: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
3: In get0(oNam, envir = ns) : internal error -3 in R_decompress1
```

**Comment by floswald** [comment]
fixed? what happend?

**Comment by michelefioretti** [comment]
It works now. Not sure why. 

Now the issue that I have is the Apps. For instance 

runTutorial('chapter3')
Error: Please run `runTutorial()` with a valid tutorial as an argument.
Valid Tutorials are: ''

runTutorial('chapter2')
Error: Please run `runTutorial()` with a valid tutorial as an argument.
Valid Tutorials are: ''

Is it possible that you are still building the package? Thanks flo!
