### ISSUE TITLE
additional version to regapp

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#20]
* Make them run the regression on standardized regressor (divided by sd). 
* Compare to correlation. 
* standardizing vars gives you correlation from β

**Comment by vviers** [comment]
In the same huge regression app or in another?

**Comment by floswald** [comment]
up to you - maybe it's the simplest to just collect all reg apps in that one existing app. just make sure that they can be easily split (variable names etc)
