### ISSUE TITLE
Mulitvariate 2: dummy variables

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#21]
* continuing from the example of #18 , now we introduce dummy vars
* a dummy is an `X \in {0,1}`, as in #18 
* the difference is that if added to another (continuous for a start) regressor, it shifts the intercept.
* do wage regression `w = a + b * gender + c * height, gender \in {0,1}` 
* I guess a tickbox with `set gender = 1` and a shifting regression line is what we want.
* any other ideas you have here, just put forward below.

**Comment by vviers** [comment]
We can totally keep this 2D, yeah?

Plotly still?
