### ISSUE TITLE
reorganize into apps

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#31]
* i set this up as a proper package now
* please file a PR that reorganizes all *standalone* apps into single file apps
* an example is shown in `/inst/shinys/reg1` for the first regapp
* create `/inst/shinys/reg2` for the second and so on
* if you are unsure about whether a certain app should be part of a tutorial eventually or be a standalone app, leave as it is. (or ask!)
thanks!

**Comment by vviers** [comment]
Can we meet on Monday to clarify exactly which apps are standalone and which are tutorials?

or we can Skype/phonecall rn if you'd like me to get on this asap

**Comment by floswald** [comment]
monday is fine, no rush. 16:30?

**Comment by vviers** [comment]
sounds good !

*Vincent Viers*
SciencesPo Paris - Euro-American program / University of California -
Berkeley
(+33) 6 32 58 78 07
​ / +1 (510) 813 8098​
vincent.viers@sciencespo.fr
​ / vincent.viers@berkeley.edu​

**Comment by floswald** [comment]
several solutions in preferred order

1. all apps live at standalone in `/inst/shinys`, are CI tested and are *sourced* into other deployments (like tutorials)
2. tell them in tutorial to `ScPoEconometrics:::run_example("reg1")`
3. copy and paste code from `/inst/shinys` to tutorials
