### ISSUE TITLE
multicollinearity app

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#40]
* illustrate with a 3d plot similar to the bottom of `06-MultipleReg.Rmd`
* fake data, N=100 or so
* slider that controls correlation between x1 and x2
* show that as the correlation increases, the resulting plane rests on an ever narrower support
* need to link that to standard error of estimates somehow

**Comment by vviers** [comment]
Quick sanity check:

When the correlation btw `x1` and `x2` increases, the OLS estimates remain the same right?

**Comment by floswald** [comment]
Yes!
