### ISSUE TITLE
change `draw` button to jump k draws ahead

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#48]
* it's cumbersome to get the histograms in the `standard_errors_simple` app
* one has to click at least 100 times to get an idea of the distribution of estimates
* can we have a second button "draw 10 samples" or "draw 20 samples" or so?

**Comment by floswald** [comment]
ok this is good. this is an important app so let's try to improve a bit further still.
1. let's do this:

```R
  output$hist_a <- renderPlotly({
    ab[3:counter$j, ] %>% plot_ly() %>%
      add_histogram(x = ~b, histnorm = "probability") %>%
      layout(xaxis = list(title = "Estimated Intercepts",
                          range = c(-3,15)),
             yaxis = list(range = c(0,0.16))
             )
  })

  output$hist_b <- renderPlotly({
    ab[3:counter$j, ] %>% plot_ly() %>%
      add_histogram(x = ~a, histnorm = "probability") %>%
      layout(xaxis = list(title = "Estimated Slopes",
                          range = c(0,5)),
             yaxis = list(range = c(0,0.16))
      )
  })
```

2. there should be a visible counter somewhere to show how many draws we've taken already. 
3. additionally, with the new button I always run out of the generated samples. can we not just start again with data from teh same dataframe?
4. it seems we need at least the entire dataframe to get a nice looking distribution, so starting again in the same df would be good.

**Comment by vviers** [comment]
1. & 2. 👍 

3. & 4. The way I do it right now means that restarting from the beginning of the df makes it impossible to "remember" where we were before...
The only way around this I think is to create a bigger data.frame in the first place – but I'm afraid this will really slow the app down... I tried yesterday and the app took a while to load on my mac.

**Comment by vviers** [comment]
Ok so here's what I think is a good compromise:

Added 1000 samples to the `standard_errors_simple` app, you can really see the estimates converge to a normal now (notice how at some point the histograms 'collapse') – this doesn't affect loading time too much

Didn't change the number of samples in the `standard_errors_N` app, which (1) would really slow everything down and (2) isn't needed when N is large which is the whole point of having them change N !

**Comment by floswald** [comment]
we need to make clear somehow that this is the linear model, i.e write out the DGP somehwere. so that it later becomes clear when we do the non normal model.
