### ISSUE TITLE
standard error for non-normal model

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#49]
this is similar to our existing app. the following list could be split into various apps.

* Now simulate a simple linear model with uniform errors and repeat the preceding experiment with different sample sizes (2, 5, 10, 100). The distribution of estimates should become normal very quickly.
* Increase N again. You should find that sd tend to 0 and estimates from different draws become identical. Define consistency as this phenomenon.
* Plot the variances of estimate as a function of N. Add 1/N to the plot. (Or std errors and 1/\sqrt{N}).
* To understand this phenomenon, calculate the variance of the mean of an iid sample. Recall that the sample mean is the OLS estimator of the most simple linear model. Statistical theory shows that this intuition applies to more complex models.
* Show then how std errors vary with the error variance and the variance of the regressor. Give the theoretical formula.
* Plot R2 as a function of N. One should now understand that in small sample, statistical error adds to the population error.

**Comment by vviers** [comment]
The way you describe it, I think it would make a lot of sense to have this as a tutorial! Sounds good?

**Comment by vviers** [comment]
> Now simulate a simple linear model with **uniform errors** and repeat the preceding experiment with different sample sizes (2, 5, 10, 100). The distribution of estimates should become normal very quickly.

Non-Normal errors? So Epsilon ~ UNIF([-5, 5]) for example?

**Comment by floswald** [comment]
Yes to both. Probably smaller range for the shock though.
