### ISSUE TITLE
chapter 3 correlation

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#5]
* make an app that plays on correlation. 

```R
library(mvtnorm)
set.seed(10)
cor = 0.9
sig = matrix(c(1,cor,cor,1),c(2,2))
ndat = data.frame(rmvnorm(n=300,sigma = sig))
x = ndat$X1
y = ndat$X2
par(pty="s")
plot(x ~ y, xlab="x",ylab="y")
```

and move `cor`

**Comment by floswald** [comment]
could we have one app for continuously joint distributed, and one for discrete?

**Comment by vviers** [comment]
Not sure what you mean by that? Like how is the discrete case going to be *visually* different from the continuous case (aside from only falling on numbers in $$\mathbb{Z}$$)?

**Comment by floswald** [comment]
yes, that is the question. here is an idea. let's go with 2 dice that are not fair. 

* have a discrete joint dist `d` in the background. basically a frequency table `1:6,1:6` where each cell shows the probability of that event occuring. fill it with non-equally distributed probabilities (i.e unfair dice)
* show the user an *empty* version of that table initially, `de`, say
* draw randomly from `d` and show in `de` where the *dice came to lie*.
* just showing the number of times the draw hits a certain cell in `de` initially, later maybe with a colorbar? 
* could make them have a guess about whether these are fair dice or not.

what do you think?

**Comment by vviers** [comment]
Are we still talking about correlation here? I don't really see how this is an example of discrete-case correlation...
I might be wrong but two dice are still independent regardless of whether they are fair or not and so I'd expect that `corr(dice1, dice2) = 0` no matter how fair or unfair they are?

Sorry about this, this is sort of confusing still. This sounds more like an example of hypothesis testing to me

**Comment by vviers** [comment]
Also while we're on the topic, one example from here (http://www.tylervigen.com/spurious-correlations) could be a fun way to introduce the *correlation is not causation* intuition early on?

**Comment by floswald** [comment]
yes, good point. *dice* was just for lack of a better term. what i meant is that they are *jointly unfair*. the probability of having (6,6) is higher than having (6,5), for example. you make up the joint distribution, that's what I meant.

i am not sure we want to talk about spurious correlation. this has to do with identification, which is kind of deep and we wanted to stay away from this for now. but let's see how this all develops.
