### ISSUE TITLE
another standardize app

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#72]
* we another *standardization*. 
* need `x - mean(x)`, same for y.
* to show that you get the same slope coefficient b as in the original case, but a zero intercept in the demeanded case.
* app should be called *demeaned-reg*
* it's mostly copy and paste from reg_standardize

**Comment by floswald** [comment]
Did you send this? Would be good to refer to this issue in the commit message so it’s easier to track down.

**Comment by vviers** [comment]
yes it's PR #73 ! Sorry about this
See you tomorrow
