### ISSUE TITLE
Suspect problem of write permission for windows

### ISSUE THREAD

**Issue by AnNguyen37** [ScPoEcon/ScPoEconometrics#87]
The problem appears when trying to install package in windows machine
```
install_github(repo = "ScPoEcon/ScPoEconometrics", force=TRUE)
Downloading GitHub repo ScPoEcon/ScPoEconometrics@master
from URL https://api.github.com/repos/ScPoEcon/ScPoEconometrics/zipball/master
Installing ScPoEconometrics
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
 --quiet CMD INSTALL  \
 "C:/Users/Public/Documents/Wondershare/CreatorTemp/RtmpSM7KA9/devtools402c37e536fb/ScPoEcon-ScPoEconometrics-b7010e6"  \
 --library="C:/Users/driss/OneDrive/Documents/R/win-library/3.5" --install-tests

ERROR: failed to lock directory 'C:/Users/driss/OneDrive/Documents/R/win-library/3.5' for modifying
Try removing 'C:/Users/driss/OneDrive/Documents/R/win-library/3.5/00LOCK-ScPoEcon-ScPoEconometrics-b7010e6'
In R CMD INSTALL
Installation failed: Command failed (3)
```

**Comment by floswald** [comment]
I think this here gets pretty close: https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Does-R-run-under-Windows-Vista_003f

**Comment by floswald** [comment]
The above FAQ points to this course of action. I think this is the first thing to try, and it's reasonably simple. Just install the R packages in a different location with write access. Like `C:\RLibrary` and set the environment variable `R_LIBS` as described here https://cran.r-project.org/bin/windows/base/rw-FAQ.html#I-don_0027t-have-permission-to-write-to-the-R_002d3_002e5_002e1_005clibrary-directory

can you give that a try with your student? This is **not** and issue with (our) `R` code.

**Comment by AnNguyen37** [comment]
Dear Florian,

Thank you for your help. Today I have checked with my student and it seems
to work.

Have a nice weekend,

Bests,

An Nguyen
