### ISSUE TITLE
Coding exercises

### ISSUE THREAD

**Issue by tyleransom** [ScPoEcon/ScPoEconometrics#99]
Hi all,

I just wanted to let you know that I've got some resources posted over at [`EconometricsLabs`](https://github.com/tyleransom/EconometricsLabs). Feel free to use any/all that you like! I'll definitely be taking a look at this book!

Tyler

**Comment by floswald** [comment]
💯 yes i had seen those when you tweeted the cheatsheet. great resource. this book here is really basic, as our undergrads have very little stats background - but hopefully I can extend it a bit more with your stuff in the next iteration!
cheers
